name: black-action
on:
  push:
    branches:
      - main

jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Black
        run: pip install black

      - name: Get changed Python files
        id: files
        run: |
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          git diff --name-only HEAD^ HEAD | grep '\.py$' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Format changed Python files
        if: env.CHANGED_FILES
        run: |
          black ${{ env.CHANGED_FILES }}
